CREATE DATABASE mydatabase;

SELECT DATABASE();

USE mydatabase;

SELECT *
FROM customer
LIMIT 5;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, 
    purchase_amount
FROM customer
WHERE discount_applied = 'yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount)
        FROM customer
      );


-- Q3. Which are the top 5 products?
SELECT 
    item_purchased,
    AVG(review_rating) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('standard', 'express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? 
-- Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END) 
        / COUNT(*) * 100, 
        2
    ) AS purchase_percentage
FROM customer
GROUP BY item_purchased
ORDER BY purchase_percentage DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal 
-- based on their total number of previous purchases.
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'new'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
            ELSE 'loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS no_of_customers
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_count
WHERE item_rank <= 3;


-- Q9. Are repeat buyers (more than 5 previous purchases) likely to subscribe?
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
